### ISSUE TITLE
Bad link to GutHub repo in npm detail

### ISSUE THREAD

**Issue by zdychacek** [tengattack/babel-preset-es2017-node7#2]
Hi,

bad link to GitHub repo here: https://www.npmjs.com/package/babel-preset-es2017-node7

It should be: "github.com/tengattack/babel-preset-es2017-node7 not "github.com/tengattack/babel-preset-es2015-node7"

Cheers.

**Comment by tengattack** [comment]
Ok, I will fix it.

Thanks
