### ISSUE TITLE
object rest not working

### ISSUE THREAD

**Issue by viktortsarevskiy** [tengattack/babel-preset-es2017-node7#4]
How to reproduce:

.babelrc
```
{
  "presets": [
    "es2017-node7",
  ],
  "plugins": []
}
```
test.js
```
require('babel-core/register');
require('./test2');
```
test2.js
```
const obj = {a:1, b: 2, c: 3};
const {...rest} = obj;
console.log(rest);
```

```console
node test.js
```

Error:
```
const { ...rest } = obj;
        ^^^
SyntaxError: Unexpected token ...
```

**Comment by tengattack** [comment]
Hi,

You can enable this feature by adding `babel-plugin-transform-es2015-destructuring`.
However, this will also transform array destructing which is already supported by node7 natively.

**Comment by viktortsarevskiy** [comment]
Thank you @tengattack.
I solved this with next set of plugins: 
`transform-es2015-destructuring transform-es2015-parameters transform-es2015-spread`
