### ISSUE TITLE
[Request] Provide an option to disable `es2015-modules-commonjs`

### ISSUE THREAD

**Issue by jhen0409** [tengattack/babel-preset-es2017-node7#5]
This will be useful for using webpack 2.

**Comment by tengattack** [comment]
ok
I found that webpack 2 supports `import` natively.

**Comment by jhen0409** [comment]
Webpack 2 supported `import` / `export` for tree-shaking ES Modules, but we need to avoid it convert to `require` / `exports` via `modules-commonjs` first.

You can see [this article](https://medium.freecodecamp.com/tree-shaking-es6-modules-in-webpack-2-1add6672f31b#.41tsu76lw).

**Comment by tengattack** [comment]
Thank you for mentioning me.
This will help: `es2015-node7/webpack2`.

**Comment by jhen0409** [comment]
👍 Thank you!

**Comment by jhen0409** [comment]
@tengattack it seems not included in the package because [it haven't add to the `files` field of package.json](https://github.com/tengattack/babel-preset-es2017-node7/blob/master/package.json#L6-L8).

**Comment by tengattack** [comment]
Sorry for that, I have added it.
